// Note: eventsource-parser doesn't export specific types for the parsed events.
// We define a custom interface based on the expected structure.

// --- API Provider Specific Stream Types (OpenAI-compatible) ---

/**
 * Represents the structure of a choice within an API provider SSE data chunk.
 */
export interface APIStreamChoice {
  delta: {
    content: string | null; // Content can be null in some initial chunks
    role?: "assistant"; // Optional role information
    audio?: {
      id?: string;
      data?: string; // Base64 encoded audio data
      transcript?: string;
    }; // Audio output from the API
  };
  finish_reason: string | null; // e.g., "stop", "length"
  index: number;
}

/**
 * Represents the parsed JSON data from a typical API provider SSE `data:` event.
 */
export interface APIParsedChunkData {
  id?: string; // Optional chunk ID
  model?: string;
  choices: APIStreamChoice[];
  // Might include usage information in the *final* chunk before [DONE]
  usage?: {
    completion_tokens?: number;
    prompt_tokens?: number;
    total_tokens?: number;
  } | null;
}

// --- eventsource-parser Related Types ---

/**
 * Represents the structure of an event object passed to the
 * onParse callback of eventsource-parser.
 */
export interface EventSourceParserEvent {
  // Removed 'type' as it seems not to be provided by the parser per TS errors
  id?: string;
  event?: string; // The event name (e.g., 'message', 'error')
  data?: string; // The event data payload
  retry?: number; // The reconnection time
}

/**
 * Type guard to check if a parsed SSE event is a data event.
 */
export function isParsedDataEvent(
  event: EventSourceParserEvent
): event is EventSourceParserEvent & { data: string } {
  // Check for the presence of the 'data' field and ensure it's a string
  return typeof event.data === "string";
}

/**
 * Type guard to check if a parsed SSE event signals stream completion.
 */
export function isCompletionEvent(
  event: EventSourceParserEvent
): event is EventSourceParserEvent & { data: "[DONE]" } {
  // Check if it's a data event and the data is the specific completion marker
  return isParsedDataEvent(event) && event.data === "[DONE]";
}

/**
 * Type guard to check if a parsed SSE event is a comment.
 * Note: eventsource-parser might not explicitly emit 'comment' types;
 * they often appear as `ParsedEvent` with type 'event' but without 'data' or 'id'.
 * This simplified check assumes comments lack data. Adjust if parser behavior differs.
 */
export function isCommentEvent(event: EventSourceParserEvent): boolean {
  // Return boolean as we can't narrow down the type much further reliably
  // Comments typically lack the 'data' field according to SSE spec.
  // We also check 'event' isn't set, as standard events usually have it.
  return (
    typeof event.data === "undefined" && typeof event.event === "undefined"
  );
}

// --- Feature API Types ---

/**
 * Payload for the onChunk callback.
 */
export interface StreamChunkPayload {
  streamId: string;
  chunk: APIParsedChunkData; // The parsed data from the SSE event
}

/**
 * Payload for the onComplete callback.
 */
export interface StreamCompletePayload {
  streamId: string;
  // Optional: Could include final usage stats if consistently available
  // usage?: APIParsedChunkData['usage'];
}

/**
 * Payload for the onError callback.
 */
export interface StreamErrorPayload {
  streamId: string;
  error: Error;
}

/**
 * Payload for the onAbort callback.
 */
export interface StreamAbortPayload {
  streamId: string;
}

// Multimodal content types for OpenAI-compatible API
export interface StreamTextContentPart {
  type: "text";
  text: string;
}

export interface StreamImageContentPart {
  type: "image_url";
  image_url: {
    url: string;
    detail?: "low" | "high" | "auto";
  };
}

export interface StreamAudioContentPart {
  type: "input_audio";
  input_audio: {
    data: string; // Base64 encoded audio data
    format?: "wav" | "mp3" | "flac" | "opus"; // Audio format hint
  };
}

export type StreamMessageContentPart = StreamTextContentPart | StreamImageContentPart | StreamAudioContentPart;

/**
 * Parameters required to initiate a chat stream request via streamChatFx.
 */
export interface StreamChatParams {
  // --- Required Stream Management ---
  streamId: string; // Unique ID generated by the consumer

  // --- Required API Provider Params (OpenAI-compatible) ---
  model: string;
  messages: ReadonlyArray<{
    role: "system" | "user" | "assistant";
    content: string | StreamMessageContentPart[]; // Support multimodal content
  }>;
  apiKey: string;
  providerApiUrl: string; // API base URL for OpenAI-compatible provider

  // --- Optional API Params (OpenAI-compatible, add others as needed) ---
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
  // Audio-specific parameters
  modalities?: ("text" | "audio")[];
  audio?: {
    voice?: string;
    format?: "wav" | "mp3" | "flac" | "opus" | "pcm";
  };
  // ... other valid OpenAI-compatible stream parameters

  // --- Callbacks ---
  onChunk: (payload: StreamChunkPayload) => void;
  onComplete: (payload: StreamCompletePayload) => void;
  onError: (payload: StreamErrorPayload) => void;
  onAbort: (payload: StreamAbortPayload) => void; // Called after abort() is successfully invoked internally

  // Note: onStart callback removed as streamId is now provided by consumer
}

/**
 * Payload for the abortStream event.
 */
export interface AbortStreamPayload {
  streamId: string;
}
