import type { Metadata } from "next";
// Removed Geist font imports
import "./globals.css";
import ThemeRegistry from "@/components/ThemeRegistry"; // Import the ThemeRegistry

// Removed Geist font setup

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Removed Geist font classNames */}
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
